openapi: 3.0.0
info:
  title: Atlas API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Development server
  - url: https://atlas-staging.rahtiapp.fi/api/v1
    description: Staging server
components:
  parameters:
    speciesId:  
      in: path
      name: speciesId
      required: true
      schema:
        type: integer
      description: MX code of the wanted species.
paths:
  /taxon:
    get:
      summary: Retrieve a list of species.
      description: Can be used to populate a list or table element.
      tags:
        - taxon
      parameters:
        - in: query
          name: group
          description: Name of the species group
          schema:
            type: array
            items:
              type: string
              enum:
                - birds
      responses:
        200:
          description: A list of queried species.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        species_id:
                          type: integer
                          description: MX-code of the species.
                          example: 25836
                        speciesFI:
                          type: string
                          description: Finnish name
                          example: Kaakkuri
                        speciesEN:
                          type: string
                          description: English name
                          example: Red-throated Diver
                        speciesSV:
                          type: string
                          description: Swedish name
                          example: Smålom
                        speciesSCI:
                          type: string
                          description: Scientific name
                          example: Gavia stellata
                        speciesAbbr:
                          type: string
                          description: Abbreviation of the scientific name
                          example: GAVSTE
                        speciesGroup_id:
                          type: integer
                          description: Group ID
                          example: 0
  /taxon/{speciesId}:
    get:
      tags:
        - taxon
      summary:
      parameters:
        - $ref: '#/components/parameters/speciesId'
  /api/v1/map/{speciesId}/atlas/3?language=fi:
    get:
      summary: Map with datapoints for birds
      description: Retrieves a map showing the breeding data of a spesified bird.
      tags:
        - map
      parameters:
    
        - name: scaling
          in: query
          schema:
            type: string
          example: '25836'
        - name: type
          in: query
          schema:
            type: string
          example: 'svg'
      responses:
        '200':
          description: Svg or png image
          content:
            image/*:
              schema:
  /map/:
    get:
      summary: List of species with datapoints on maps.
      description: Retrieves a list of species with at least one datapoint on some map and a link to that endpoint.
      tags: 
        - map
      responses:
        '200':
          description: A list of all species with datapoints on maps.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        species_id:
                          type: integer
                          description: MX-code of the bird.
                          example: 25836
                        map_endpoint:
                          type: string
                          description: URL address of the species' map endpoint.
                          example: /api/v1/map/25836/atlas/3?language=fi
  /map/{speciesId}:
    get:
      summary: List of different subcollections for maps
      parameters:
        - $ref: '#/components/parameters/speciesId'
      description: Retrieves a list of subcollections of maps; atlas maps and their comparison maps.
      tags: 
        - map
      responses:
        '200':
          description: A list of all birds with datapoints on maps.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        subcollection:
                          type: string
                          description: Name of the subcollection
                          example: Atlas
                        subcollection_endpoint:
                          type: string
                          description: URL address for the subcollection endpoint.
                          example: /api/v1/map/25836/atlas/
  /map/{speciesId}/atlas:
    get:
      parameters:
        - $ref: '#/components/parameters/speciesId'
      summary: List of different subcollections for maps
      description: Retrieves a list of subcollections of maps; atlas maps and their comparison maps.
      tags: 
        - map
      responses:
        '200':
          description: A list of all birds with datapoints on maps.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        subcollection:
                          type: string
                          description: Name of the subcollection
                          example: Atlas
                        subcollection_endpoint:
                          type: string
                          description: URL address for the subcollection endpoint.
                          example: /api/v1/map/25836/atlas/3?